- hosts: localhost
  connection: local
  gather_facts: no
  vars:
#    username: "{{ lookup('onepassword', 'test', field='username', vault='CS AWX') }}"
#    password: "{{ lookup('onepassword', 'test', field='password', vault='CS AWX') }}"
    username: "{{ lookup('onepassword', 'test', field='username', vault='CS AWX', master_password='Slavchik_300694') }}"
    password: "{{ lookup('onepassword', 'test', field='password', vault='CS AWX', master_password='Slavchik_300694') }}"

  tasks:
  - name: "retrieve password and username from 1password" 
    debug:
      msg:
#        - "{{ lookup('onepassword', 'test', field='username', vault='CS AWX', master_password='Slavchik_300694', username='ydrabyk@cisco.com', secret_key='A3-SVQ9DK-3JRQLV-ASKLK-7L9MG-WVNQP-B25CK') }}"
        - "user name is {{username}}"
        - "password is {{password}}"
