- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    username: "{{ lookup('onepassword', 'test', field='username', vault='CS AWX', subdomain='{{op_subdomain}}', master_password='{{op_master_password}}', username='{{op_username}}', secret_key='{{op_secret_key}}') }}"
    password: "{{ lookup('onepassword', 'test', field='password', vault='CS AWX', subdomain='{{op_subdomain}}', master_password='{{op_master_password}}', username='{{op_username}}', secret_key='{{op_secret_key}}') }}"
#    username: "{{ lookup('onepassword', 'test', field='username', vault='CS AWX') }}"
#    password: "{{ lookup('onepassword', 'test', field='password', vault='CS AWX') }}"
#    username: "{{ lookup('onepassword', 'test', field='username', vault='CS AWX', master_password='Slavchik_300694') }}"
#    password: "{{ lookup('onepassword', 'test', field='password', vault='CS AWX', master_password='Slavchik_300694') }}"
#    username: "{{ lookup('onepassword', 'test', field='username', vault='CS AWX', master_password='Slavchik_300694', username='ydrabyk@cisco.com', secret_key='A3-SVQ9DK-3JRQLV-ASKLK-7L9MG-WVNQP-B25CK') }}"
#    password: "{{ lookup('onepassword', 'test', field='password', vault='CS AWX', domain='https://my.1password.com', master_password='Slavchik_300694', username='ydrabyk@cisco.com', secret_key='A3-SVQ9DK-3JRQLV-ASKLK-7L9MG-WVNQP-B25CK') }}"
#
  tasks:
  - name: "retrieve password and username from 1password" 
    debug:
#      var: lookup('onepassword', 'test', field='username', vault='CS AWX', subdomain='{{op_subdomain}}', master_password='{{op_master_password}}', username='{{op_username}}', secret_key='{{op_secret_key}}')
      var: password
#        - password
#        - username
#      msg:
#      var: lookup('onepassword', 'test', field='username', vault='CS AWX', subdomain='my', master_password='Slavchik_300694', username='ydrabyk@cisco.com', secret_key='A3-SVQ9DK-3JRQLV-ASKLK-7L9MG-WVNQP-B25CK')
#        - "user name is '{{username}}'"
#        - "password is {{password}}"
